### PR TITLE
fix: Unordered arrays of objects with PRESENCE fix

### LINKED ISSUE #39: [BUG] Fail to compare <<UNORDERED>> arrays where elements have <<PRESENCE>>
### What exactly did you do?

Compare `<<UNORDERED>>` JSON arrays where the elements are objects and the expectation for some fields only checks for `<<PRESENCE>>`.

Test example:

```go
func TestUNORDEREDwithPRESENCE(t *testing.T) {
	act := `{
		"data": [
			{ "foo": 1, "bar": 2 },
			{ "foo": 11, "bar": 22 }
		]
	}`
	exp := `{
		"data": [
			"<<UNORDERED>>",
			{ "foo": 11, "bar": "<<PRESENCE>>" },
			{ "foo": 1, "bar": "<<PRESENCE>>" }
		]
	}`
	ja := jsonassert.New(t)
	ja.Assertf(act, exp)
}
```

See test examples with some sanity in [this Go Playground](https://go.dev/play/p/OTV-Bf3ZOLk).

### What did you expect would happen?

The test should pass - I should be able to compare `<<UNORDERED>>` arrays having elements with `<<PRESENCE>>` in them.

### What actually happened?

```console
=== RUN   TestUNORDEREDwithPRESENCE
    prog.go:81: actual JSON at '$.data[0]' contained an unexpected element: {"bar":2,"foo":1}
    prog.go:81: actual JSON at '$.data[1]' contained an unexpected element: {"bar":22,"foo":11}
    prog.go:81: expected JSON at '$.data[0]':
        {"bar":"\u003c\u003cPRESENCE\u003e\u003e","foo":11}
        was missing from actual payload
    prog.go:81: expected JSON at '$.data[1]':
        {"bar":"\u003c\u003cPRESENCE\u003e\u003e","foo":1}
        was missing from actual payload
--- FAIL: TestUNORDEREDwithPRESENCE (0.00s)
FAIL
```

### Additional info

- Output from `go version`: `go version go1.18.2 darwin/arm64`
- Version of this package: `v.1.1.0`

As can be seen in the [Go Playground example](https://go.dev/play/p/OTV-Bf3ZOLk), I did some sanity tests, and it seems that   `<<UNORDERED>>` and `<<PRESENCE>>` work well for the example above, **except** for when they are mixed together.
Looking in the code, it seems to be caused by. the difference between [`Asserter.checkArrayUnordered`](https://github.com/kinbiko/jsonassert/blob/main/array.go#L52) and [`Asserter.checkArrayOrdered`](https://github.com/kinbiko/jsonassert/blob/main/array.go#L88). The unordered version uses [`Asserter.deepEqual`](https://github.com/kinbiko/jsonassert/blob/main/array.go#L65), whereas the ordered version uses [`Asserter.pathassertf`](https://github.com/kinbiko/jsonassert/blob/main/core.go#L13).

### PR DESCRIPTION
**Pull request by kinbiko**
Closes #39

## Checklist

- [x] I have done a self-review of the PR.

### CODE REVIEW

File: helper.go [hunk 1]
```diff
@@ -12,3 +12,18 @@ type noopHelperTT struct {
...
+
+// deepEqualityPrinter is a utility Printer that lets the jsonassert package
+// verify equality internally without affecting the external facing output,
+// e.g. to verify where one potential candidate is matching or not.
+type deepEqualityPrinter struct{ count int }
+
+func (p *deepEqualityPrinter) Errorf(msg string, args ...interface{}) { p.count++ }
+func (p *deepEqualityPrinter) Helper()                                { /* Intentional NOOP */ }
+
+func (a *Asserter) deepEqual(act, exp interface{}) bool {
```
Comment (kinbiko) [inline helper.go:24]: The performance here is probably *significantly* worse, depending on just how much nesting is going on. Performance is explicitly not a goal of this package, but there may be some wins around doing a naive `deepEqual` like before and only doing this more expensive check in case of failures only. Would need to benchmark etc., so will leave this as is for now. Also not committing to ever fixing the perf in the future.

Comment (kinbiko) [reply helper.go:24]: Actually the above would be a tradeoff b/w breadth/depth. Indeed, benchmarking would be required before implementing anything like that.
